name: platform
description: "platform for c++"
version: 1.0.8

authors: ["Rudolf Mueller"]
license: MIT
websites: ["https://rudolfmuller.github.io/clibx-package-manager/","https://github.com/rudolfmuller/platform-lib/"]

dependencies: ["https://github.com/rudolfmuller/platform-lib.git"]
