name: platform
description: "platform for c++"
version: 1.0.8

authors: ["Rudolf Mueller"]
license: MIT
websites: ["https://rudolfmuller.github.io/clibx-package-manager/","https://github.com/rudolfmuller/platform-lib/"]


build-mode: static # shared | static | simple
build-compiler: g++ # g++ | gcc
build-cflags: [-O2, -Wall]
build-dependencies: ["syshit@1.0.1"]
build-include-directory: "include/"
build-source-files: ["source/platform.cpp", "source/foo.cpp"]
